### ISSUE TITLE
[P40 Lite e] Facial recognition hardware not detected

### ISSUE THREAD

**Issue by mstankov** [HMS-Core/hms-FIDO-demo-java#3]
Hi guys,

I'm trying to implement facial recognition via FaceManager API on a react-native app (java native android module). The phone apparently supports facial recognition but here's the issue:
**FaceManager**'s `hasFaceRecognition` returns **true**, `hasEnrolledTemplates` also returns **true** but `isHardwareDetected` returns **false** and `auth` returns error **1** (**FACE_ERROR_HW_UNAVAILABLE**). Why does it not detect the phone's hardware?

**android.permission.USE_BIOMETRIC** and **android.permission.CAMERA** are both granted.

Any help is appreciated, thanks!

Have a great day.

**Comment by sunzlluffy** [comment]
Hi，
pls make sure use the FIDO bioauthn SDK，  What is the SDK version?

**Comment by mstankov** [comment]
> Hi，
> pls make sure use the FIDO bioauthn SDK， What is the SDK version?

Hi @sunzlluffy @chongye89 , I'm using `com.huawei.hms:fido-bioauthn-androidx` version **5.2.0.301**

**Comment by mstankov** [comment]
@sunzlluffy @chongye89 I just implemented a separate module for FIDO2 using [this](https://developer.huawei.com/consumer/en/codelab/HMSCoreFIDO2/index.html#5) guide and this is what I noticed:
1. `mFido2Client.isSupported()` returns **true**, since I've enabled it in the project's SDK list
2. `mFido2Client.hasPlatformAuthenticators()` returns **true** as well
3. `mFido2Client.getPlatformAuthenticators()` returns the device's fingerprint UVM only (`UVM_FINGERPRINT`)

So apparently both libraries are telling me that the device (Huawei P40 Lite E) does not support facial recognition but then again, in the device's settings, the user can configure facial recognition and use it to unlock the phone. Why is that? :) Please help, thanks!

**Comment by sunzlluffy** [comment]
Hi, @mstankov , I understand your question. Currently, only phones that support 3D facial features are Mate 20 Pro, Mate 30 Pro, and Mate 40 Pro. REF:https://developer.huawei.com/consumer/en/doc/development/HMS-Guides/FIDO2_FAQ

**Comment by mstankov** [comment]
@sunzlluffy thanks for answering! Why does the Huawei P40 Lite E for example claim to support Face Recognition and can be configured then to be used for unlocking the user's phone? Is this face recognition considered to be 2D and is software-only, thus not as reliable as the 3D Face Recognition supported by FIDO2?

**Comment by sunzlluffy** [comment]
Hi @mstankov ，For P40 phones, 2D facial recognition is used. FIDO bioauthn and FIDO2 SDK support only 3D authentication. In the future, 2D facial recognition may be supported.
